name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get yarn cache dir
        id: yarnCache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn
        with:
          path: ${{ steps.yarnCache.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('backend/yarn.lock') }}
      - name: Install dependencies
        run: |
          cd backend
          yarn install
      - name: Test and build
        run: |
          cd backend
          yarn lint
          yarn test
          yarn build
